Feature/BSA-272/Allow to hide "Logout" and "Home" buttons for the delivery execution
oat-sa/extension-tao-delivery pull request #494
Opened 2020-10-13 13:19 UTC by shpran

Relates to: [BSA-272](https://oat-sa.atlassian.net/browse/BSA-272)

**Changes:**
* added possibility to configure the visibility of the "Logout" and "Home" buttons for the delivery execution header;
* added default configuration to show this buttons.

**Companion PR:**

2020-10-14 07:15 UTC, bziondik requested changes
Have error on Update
![image](https://user-images.githubusercontent.com/25976342/95955823-1f245700-0e06-11eb-9d55-c51a46747a64.png)

2020-10-14 07:38 UTC, bziondik approved these changes
Checked locally, works as expected

2020-10-15 09:13 UTC, SergiiTao commented on scripts/tools/ConfigureDeliveryExecutionHeader.php
> + *
very meaningful docblock :)

2020-10-15 09:18 UTC, SergiiTao commented on scripts/tools/ConfigureDeliveryExecutionHeader.php
> +        $config['hideHomeButton'] = $this->getOption(self::OPTION_HIDE_HOME_BUTTON);
I think we can use constants as keys also, right?

2020-10-15 09:21 UTC, shpran commented on scripts/tools/ConfigureDeliveryExecutionHeader.php
> +        $config['hideHomeButton'] = $this->getOption(self::OPTION_HIDE_HOME_BUTTON);
Right :)
Thanks for the remark

2020-10-15 09:26 UTC, SergiiTao requested changes
minor cs fixes

2020-10-16 08:46 UTC, shpran commented on migrations/Version202010131343168613_taoDelivery.php
> +final class Version202010131343168613_taoDelivery extends AbstractMigration
```suggestion
final class Version202010131343168613_taoDelivery extends AbstractMigration
```

2020-10-16 08:47 UTC, shpran commented on scripts/tools/ConfigureDeliveryExecutionHeader.php
> +class ConfigureDeliveryExecutionHeader extends ScriptAction
```suggestion
class ConfigureDeliveryExecutionHeader extends ScriptAction
```

2020-10-16 08:47 UTC, shpran commented on scripts/tools/ConfigureDeliveryExecutionHeader.php
> +/**
```suggestion
```

2020-10-16 09:09 UTC, SergiiTao requested changes

2020-10-16 09:09 UTC, SergiiTao commented on controller/DeliveryServer.php
> +        $headerConfig = $extension->getConfig('deliveryExecutionHeader');
please consider using a proper config repository with validation. 
looking at `$headerConfig = $extension->getConfig('deliveryExecutionHeader');` it is not obvious what is the type, what is inside, is it valid, etc.

2020-10-16 09:13 UTC, shpran commented on controller/DeliveryServer.php
> +        $headerConfig = $extension->getConfig('deliveryExecutionHeader');
Do you have any suggestions?

2020-10-16 09:18 UTC, SergiiTao commented on controller/DeliveryServer.php
> +        $headerConfig = $extension->getConfig('deliveryExecutionHeader');
`class DeliveryExecutionConfig extends ConfigurableService
public function isHomeButtonHidden(): bool;
...
`
or may be we already have something like this

2020-10-16 11:11 UTC, shpran commented on controller/DeliveryServer.php
> +        $headerConfig = $extension->getConfig('deliveryExecutionHeader');
Done

2020-10-20 13:13 UTC, SergiiTao requested changes

2020-10-20 13:13 UTC, SergiiTao commented on model/execution/DeliveryExecutionConfig.php
> +        return (bool) $this->getOption(self::OPTION_HIDE_HOME_BUTTON, false);
as in the previous PR 
(bool) doesn't guarantees a correct value. please consider validating input values and cast types in a safer way

2020-10-21 08:44 UTC, SergiiTao requested changes

2020-10-21 08:44 UTC, SergiiTao commented on model/execution/DeliveryExecutionConfig.php
> +    public static function toBool($value): bool
don't reinvent a wheel 
`filter_var($var, FILTER_VALIDATE_BOOLEAN)` or `filter_var($var, FILTER_VALIDATE_BOOLEAN, FILTER_NULL_ON_FAILURE)` works just fine

2020-10-21 08:49 UTC, shpran commented on model/execution/DeliveryExecutionConfig.php
> +    public static function toBool($value): bool
Oh, forgot about this function, thanks

2020-10-21 12:51 UTC, SergiiTao approved these changes
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-10-21 13:16 UTC, merged