Feature/tr 858/rtl delivery header
oat-sa/extension-tao-delivery pull request #503
Opened 2021-06-01 14:12 UTC by lecosson

**Related to:** https://oat-sa.atlassian.net/browse/TR-858

**Changes:**
- added styles and initial code o implement RTL feature for felivery headers

**How to check:**
- open delivery index page and/or launch delivery
- ensure header elements order and position is reverted

**Note:**
- PR requires feature implemented in [TR-857](https://oat-sa.atlassian.net/browse/TR-857)

**Requires:**
 - [ ] mentioned in **Note** section

2021-06-02 10:10 UTC, jsconan requested changes
It works, but the implementation may not apply on any configuration. Moreover, the way the RTL is applied may have side effect. Please have a look on mu comments below.
The styling looks to apply on a particular scheme, but looks too hacky.

2021-06-02 10:10 UTC, jsconan commented on views/scss/inc/rtl/_header.scss
> +          background: #666;
**nitpick:** This color should pass through a variable

2021-06-02 10:10 UTC, jsconan commented on views/scss/inc/rtl/_header.scss
> +      &:nth-last-child(2) {
**thought:** Why is it such precise in the selector? Will this apply on any configuration? I didn't see it applied on my testing env.

2021-06-02 10:10 UTC, jsconan commented on views/scss/inc/rtl/_header.scss
> +        [role=button]:before {
**thought:** Why is it on the first child only? Did you try to affect the seperator? If so, there is dedicated class for this: `sep-before`;

2021-06-02 12:41 UTC, btamas requested changes

2021-06-02 12:41 UTC, btamas commented on views/scss/inc/rtl/_header.scss
> +    transform: scaleX(-1);
I think it is not the best way to implement RTL mode. It works in this particular case, but if it will contain anything else that a logo, it should rotated again to have the correct form.

2021-06-03 14:39 UTC, jsconan approved these changes
It works fine. Good job!
Just one remark about over-engineered CSS selector.

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-06-03 14:39 UTC, jsconan commented on views/js/controller/DeliveryServer/index.js
> +                const menuItemSelector = '.delivery-scope[dir=rtl] .content-wrap [role=menubar] > [role=menu] > .settings-menu > .plain > *';
**question:** Is it required to use such a long selector?
I'm pretty sure something shorter would work as well, something like: 
```javascript
const menuItemSelector = '.delivery-scope[dir=rtl] .settings-menu li';
```

2021-06-04 08:17 UTC, meefox requested changes

2021-06-04 08:17 UTC, meefox commented on views/js/controller/DeliveryServer/index.js
> +                const menuItemSelector = '.delivery-scope[dir=rtl] .content-wrap [role=menubar] > [role=menu] > .settings-menu > .plain > *';
This kind of selector is very dangerous they are very coupled to the structure.
As well it is a very fragile approach and makes huge difficulties for maintainability. 

I would highly suggest using shorter as possible or even one selector for js logic if necessary and decoupled from styling classes.

I would even consider using a dedicated namespace of selectors for logic only like "js_menu_item" where is needed, you be independent of structure and makes easy to refactor CSS or js.

2021-06-04 08:18 UTC, meefox requested changes

2021-06-04 08:18 UTC, meefox commented on views/js/controller/DeliveryServer/index.js
> +                const menuItemSelector = '.delivery-scope[dir=rtl] .content-wrap [role=menubar] > [role=menu] > .settings-menu > .plain > *';
- [ ] please, use shorter selector

2021-06-04 09:13 UTC, meefox approved these changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-06-04 09:15 UTC, btamas approved these changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-06-04 09:19 UTC, merged