fix: TR-3034. Change icons for RTL mode
oat-sa/extension-tao-delivery pull request #528
Opened 2021-11-29 12:10 UTC by svoronuk

Related to: https://oat-sa.atlassian.net/browse/TR-3034

How to test:
1. Add test taker with Arabic language
2. Publish test and assign created user
3. Check the icons styles according to ACs

2021-11-29 19:31 UTC, olga-kulish approved these changes
Works well 

- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-11-30 11:27 UTC, oatymart reviewed
The play icon flip is present. Please check which way the page header should flow, it's not mentioned anywhere.

2021-11-30 11:27 UTC, oatymart commented on views/scss/delivery.scss
> +
Why did you remove the `inc/rtl` import? Seems like that contains [a file](https://github.com/oat-sa/extension-tao-delivery/blob/master/views/scss/inc/rtl/_header.scss#L26) which affects very much the header layout in RTL mode, including the menu items and logout icon (including changes applied [very recently](https://github.com/oat-sa/extension-tao-delivery/pull/522))...

However, don't trust me on this - better to check with BA.

2021-12-01 07:07 UTC, svoronuk commented on views/scss/delivery.scss
> +
It was made by accident. I'll fix this.

2021-12-01 08:47 UTC, oatymart requested changes
I had another thought about where the code should live...

2021-12-01 08:47 UTC, oatymart commented on views/scss/delivery.scss
> +    }
The solution works. However, I'm still not sure your code is in the right place. Seems to me, previous developers intended that all `rtl` styles should go inside `inc/rtl` folder. I would suggest to create a file `inc/rtl/_content.scss` and put the block inside it. WDYT?

2021-12-01 13:56 UTC, svoronuk commented on views/scss/delivery.scss
> +    }
Sounds reasonable. I'll modify it.

2021-12-01 14:06 UTC, oatymart approved these changes
Looks good now!

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [ ] Documentation is updated according to changes (if applicable)

2021-12-03 13:13 UTC, merged