feat: KVDeliveryExecution used to store  metadata
oat-sa/extension-tao-delivery pull request #549
Opened 2022-08-01 13:08 UTC by bartlomiejmarszal

Create a way to store metadata in KV storage with delivery execution

2022-08-01 13:51 UTC, gabrielfs7 commented on model/execution/exception/MissingMetadataProperty.php
> +class MissingMetadataProperty
For clarity and convention (since we use like this already), do you think having a suffix `Exception` in the class name makes sense?

```suggestion
class MissingMetadataPropertyException extends Exception
```

2022-08-01 13:55 UTC, gabrielfs7 commented on model/execution/DeliveryExecutionMetadataInterface.php
> +    public function getAllMetadata(): array;
What is the `array`? Do not we have specific object to map it?

2022-08-01 13:55 UTC, gabrielfs7 commented on model/execution/DeliveryExecutionMetadataInterface.php
> +    public function addMetadata(array $metadata): void;
Would not be more consistent to have an specific object instead of an array?

2022-08-01 13:56 UTC, gabrielfs7 commented on model/execution/DeliveryExecutionMetadataInterface.php
> +    public function getMetadata(string $metadataId): string;
Would not be more consistent to return a metadata object instead of a string?

2022-08-01 18:58 UTC, bartlomiejmarszal commented on model/execution/DeliveryExecutionMetadataInterface.php
> +    public function getAllMetadata(): array;
In my opinion array will be more flexible in order to store multiple type of data. We may store here float, string, integer or even arrays. Do you think object will be better solution here?

2022-08-01 18:59 UTC, bartlomiejmarszal commented on model/execution/DeliveryExecutionMetadataInterface.php
> +    public function addMetadata(array $metadata): void;
Would that specific object store specific data inside? StringMetadata, FloatMetadata, ArrayMetadata?

2022-08-02 06:07 UTC, gabrielfs7 commented on model/execution/DeliveryExecutionMetadataInterface.php
> +    public function addMetadata(array $metadata): void;
Having an unknown array can cause confusion and allow developers to transfer data in inconsistent way. An object is a better way of defining a contract and is still extensible in the feature, cause you can add more methods, attributes (example: widget, validation type, etc). You can even define in the class how serialization rules.

``` php
class Medatada implements JsonSerializable {
      private string $id;
      private string $value;

     public function getId(): string;
     public function getValue(): mixed;
     public function jsonSerialize(): array // can be used in the API as how to expose this object
}
```

Would be also useful to have a collection to represent this object 

``` php
class MedatadaCollection extends ArrayIterator implements JsonSerializable {
     public function jsonSerialize(): array // can be used in the API as how to expose a collection of this object
}
```

2022-08-02 08:27 UTC, andreluizmachado requested changes

2022-08-02 08:27 UTC, andreluizmachado commented on test/unit/model/execution/KVDeliveryExecutionTest.php
> +    private function assertDataset(KVDeliveryExecution $subject)
I guess you missed void return types into some methods

2022-08-02 08:27 UTC, andreluizmachado commented on model/execution/exception/NonExistentMetadataException.php
> +}
empty line

2022-08-02 08:27 UTC, andreluizmachado commented on model/execution/DeliveryExecutionMetadataInterface.php
> +    public function getAllMetadata(): array;
Why not an Iterator Object? this would be nice to encapsulate logic on MetadaCollection in case we need it.

2022-08-02 08:27 UTC, andreluizmachado commented on model/execution/KVDeliveryExecution.php
> +            common_Logger::w($exception->getMessage());
Can we use LoggerInterface with DI instead?

2022-08-02 08:27 UTC, andreluizmachado commented on model/execution/KVDeliveryExecution.php
> +    public function getMetadata(string $metadataId): string
Maybe add PHPDoc for the exception thrown

2022-08-02 08:27 UTC, andreluizmachado commented on model/execution/DeliveryExecutionMetadataInterface.php
> +}
missing empty line

2022-08-02 08:27 UTC, andreluizmachado commented on model/execution/DeliveryExecutionMetadataInterface.php
> +    public const PROPERTY_METADATA = 'http://www.tao.lu//Ontologies/Metadata';
maybe specify the property type as you did on unit test.

2022-08-02 13:43 UTC, bartlomiejmarszal commented on model/execution/KVDeliveryExecution.php
> +            common_Logger::w($exception->getMessage());
This class does not follow DI standard. It's just implementation attribute for one of delivery execution. Therefore I need to keep it as it is.

2022-08-03 07:37 UTC, andreluizmachado requested changes

2022-08-03 07:37 UTC, andreluizmachado commented on model/execution/KVDeliveryExecution.php
> +            return $collection;
I'd include the return between lines 217, and 218 just in case we forget to catch some exceptions. In this case, the method would return void and this would throw a fatal error.

2022-08-03 07:37 UTC, andreluizmachado commented on model/execution/KVDeliveryExecution.php
> +        foreach ($this->getData(DeliveryExecutionMetadataInterface::PROPERTY_METADATA) as $metadata) {
Are we sure that getData returns are always array/Iterable?

2022-08-03 07:37 UTC, andreluizmachado commented on model/execution/metadata/Metadata.php
> +    public function jsonSerialize()
```suggestion
    public function jsonSerialize(): array
```

2022-08-03 07:37 UTC, andreluizmachado commented on model/execution/metadata/MetadataCollection.php
> +        foreach ($items as $item) $this->items[$item->getMetadataId()] = $item;
```
andremachado@OATs-MacBook-Pro /tmp % phpcs --standard=PSR12 MetadataCollection.php                                                                                                                                         

FILE: /private/tmp/MetadataCollection.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 37 | ERROR | [x] Inline control structures are not allowed
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

2022-08-03 08:22 UTC, bartlomiejmarszal commented on model/execution/KVDeliveryExecution.php
> +        foreach ($this->getData(DeliveryExecutionMetadataInterface::PROPERTY_METADATA) as $metadata) {
Yes

2022-08-03 08:25 UTC, bartlomiejmarszal commented on model/execution/metadata/MetadataCollection.php
> +        foreach ($items as $item) $this->items[$item->getMetadataId()] = $item;
Why would we not allow Inline control structures?

2022-08-03 10:13 UTC, pnal requested changes

2022-08-03 10:13 UTC, pnal commented on model/execution/DeliveryExecutionMetadataInterface.php
> +    public const PROPERTY_METADATA = 'http://www.tao.lu//Ontologies/Metadata';
Should the name be:
```suggestion
    public const PROPERTY_METADATA = 'http://www.tao.lu/Ontologies/TAODelivery.rdf#DeliveryExecutionMetadata';
```
to unify it with possible RDF implementation?

2022-08-03 10:13 UTC, pnal commented on test/unit/model/execution/KVDeliveryExecutionTest.php
> +        $this->keyValueServiceMock->method('getData')->willReturn($this->dataset);
could you also add a case when it throws `common_exception_NotFound`?

2022-08-03 11:01 UTC, andreluizmachado approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2022-08-03 13:54 UTC, pnal approved these changes
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2022-08-04 05:54 UTC, gabrielfs7 commented on .github/workflows/continuous-integration.yaml
> -        php-version: [ '7.4', '8.0', '8.1' ]
Why was it removed, we expect that the build will break for PHP other than 7.4 for now, but we still should keep it there. @wazelin can provide more details.

2022-08-04 05:58 UTC, gabrielfs7 commented on model/execution/metadata/Metadata.php
> +    private string $metadataId;
I am not sure yet we are supporting only PHP 7.4+ now.

2022-08-04 05:58 UTC, gabrielfs7 commented on model/execution/metadata/MetadataCollection.php
> +    private array $items = [];
https://github.com/oat-sa/extension-tao-delivery/pull/549/files#r937375965

2022-08-04 05:59 UTC, gabrielfs7 commented on test/unit/model/execution/metadata/MetadataCollectionTest.php
> +    private Metadata $metadata;
https://github.com/oat-sa/extension-tao-delivery/pull/549/files#r937375965

2022-08-04 06:05 UTC, gabrielfs7 commented on model/execution/KVDeliveryExecution.php
> +                $collection->jsonSerialize()
For better querying and compatibility with other databases, I was imagining we would save each metadata as a new line(s) rather than a JSON (The Json format would be used for the API only). I know it is possible to query JSON with postgres if the field is properly set in the DB, but I am not sure that is the case. 

We are now creating a segregation here on metadata (schema properties) used in TAO to a new sort of metadata. 

I am not stating it as a blocker, but I think we could have used current property schema feature to leverage for this feature + prepare for the future.

2022-08-04 08:35 UTC, bartlomiejmarszal commented on .github/workflows/continuous-integration.yaml
> -        php-version: [ '7.4', '8.0', '8.1' ]
Why we can't keep only 7.4 for now and later add 8+?

2022-08-04 08:39 UTC, wazelin commented on model/execution/metadata/Metadata.php
> +    private string $metadataId;
What's wrong here with PHP 7.4 compatibility?

2022-08-04 08:45 UTC, wazelin commented on .github/workflows/continuous-integration.yaml
> -        php-version: [ '7.4', '8.0', '8.1' ]
This repo gets updated quite infrequently.
Considering there's nothing to be updated in this extension to support php 8+, and the only issue is generis/tao-core, it will simply start working once generis/tao-core updates have been released.

2022-08-04 08:47 UTC, wazelin commented on .github/workflows/continuous-integration.yaml
> -        php-version: [ '7.4', '8.0', '8.1' ]
Moreover.
You can check right now if your new code runs well with PHP 8+ if you add the following dependencies to `composer.json`
```
    "require-dev": {
      "oat-sa/generis": "dev-php8-migration as v16.0.0",
      "oat-sa/tao-core": "dev-php8-migration as v51.0.0"
    }
```

2022-08-04 10:09 UTC, bartlomiejmarszal commented on .github/workflows/continuous-integration.yaml
> -        php-version: [ '7.4', '8.0', '8.1' ]
I did:
https://github.com/oat-sa/extension-tao-delivery/pull/549/commits/5d16fe92fe489cdce67ba8d818d501aa40fe352d

2022-08-04 10:10 UTC, bartlomiejmarszal commented on model/execution/metadata/Metadata.php
> +    private string $metadataId;
tao-community has a defined platform for PHP 7.2.5
https://github.com/oat-sa/tao-community/blob/be597fdae708ae534f3e3f26ea869e0add0d5e28/composer.json#L6

2022-08-04 10:16 UTC, gabrielfs7 commented on model/execution/metadata/Metadata.php
> +    private string $metadataId;
Aa Bart mentioned, it is compatible, my point is that only after the PHP 8 migration (AKA PHP 7.4+ migration) we are supporting only PHP 7.2 for some customers / environments. So I am not sure this is the right moment to start adding PHP 7.4 features.

2022-08-04 11:11 UTC, bartlomiejmarszal commented on model/execution/metadata/Metadata.php
> +    private string $metadataId;
I think we could change that with the September release, so I suggest keeping it as it is. I heard that only few clients are using PHP 7.2 but they are using old authoring from sprint 96 or smoothing similar also it should not impact them.

2022-08-09 08:28 UTC, andreluizmachado commented on model/execution/KVDeliveryExecution.php
>      public function jsonSerialize()
```suggestion
    public function jsonSerialize(): array
```

2022-08-09 08:28 UTC, andreluizmachado commented on model/execution/implementation/KeyValueService.php
> +    public function getDeliveryExecutionKeyValue(string $deliveryExecutionUri): KVDeliveryExecution
```suggestion
    private function getDeliveryExecutionKeyValue(string $deliveryExecutionUri): KVDeliveryExecution
```

2022-08-09 14:44 UTC, merged