feat: allow to provide delivery execution id in parameters
oat-sa/extension-tao-delivery pull request #555
Opened 2022-09-13 14:32 UTC by kilatib

# [TR-4622](https://oat-sa.atlassian.net/browse/TR-4622)

## Description
Looks like DE was created always in RDS incrased of be created by need settings 

## Step to reproduce
1. Log in as Admin and choose 'Results' tab
2. Select completed delivery and click 'View' button

## Development impact 
1. Add possibility to provide id for delivery execution  

## Demo 

https://user-images.githubusercontent.com/2750628/189927170-c248c4d4-714d-4f62-9642-3b47d386980d.mov

2022-09-13 14:38 UTC, gabrielfs7 commented on model/execution/implementation/KeyValueService.php
> +    public function spawnDeliveryExecution($label, $deliveryId, $userId, $status, $identifier = null)
We are missing `oat\taoDelivery\model\execution\OntologyService::spawnDeliveryExecution`. Maybe we should create an interface and stick to it to not forget anymore?

2022-09-13 14:38 UTC, gabrielfs7 commented on model/execution/implementation/KeyValueService.php
> +    public function spawnDeliveryExecution($label, $deliveryId, $userId, $status, $identifier = null)
Do not forget the tests too, please

2022-09-13 14:46 UTC, kilatib commented
@wazelin and @poyuki 
This PR could be completely removed if we don't have need to store `resultId` in our system completely same as `lis_result_sourcedid`(second part) value

2022-09-13 15:02 UTC, kilatib commented on model/execution/implementation/KeyValueService.php
> +    public function spawnDeliveryExecution($label, $deliveryId, $userId, $status, $identifier = null)
thank you for mentioned it

2022-09-14 14:05 UTC, poyuki commented on model/execution/DeliveryExecutionServiceInterface.php
> +}
empty line

2022-09-14 14:43 UTC, kilatib commented on model/execution/implementation/KeyValueService.php
> +    public function spawnDeliveryExecution($label, $deliveryId, $userId, $status, $identifier = null)
It is not a lot how we could get from such unit test I did on way how it was before

2022-09-14 14:47 UTC, kilatib commented on test/unit/model/execution/implementation/KeyValueServiceTest.php
> +            ->getMockBuilder(KeyValueServiceTest::class)
oh, sorry yes

2022-09-14 14:49 UTC, gabrielfs7 commented on test/unit/model/execution/OntologyServiceTest.php
> +            ->getMockBuilder(OntologyService::class)
I recommend to not use the original class instead of mock it. You can mock the dependencies instead.

2022-09-14 15:40 UTC, kilatib commented on test/unit/model/execution/OntologyServiceTest.php
> +            ->getMockBuilder(OntologyService::class)
Just did it as others classes here , but I think you are right

2022-09-16 12:20 UTC, poyuki approved these changes
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2022-09-16 12:20 UTC, wazelin requested changes
The original problem hasn't been solved yet, @kilatib.

Since the KeyValue storage persist the delivery executions with a prefix, TAO still cannot read the results XML when executing `RetrieveResultsTask`.

This can be solved by either removing the prefixes from KV- and RDS-stored delivery executions, or by adding another method into https://github.com/oat-sa/extension-tao-delivery/blob/master/model/execution/DeliveryExecution.php that will allow fetching an unprefixed ID. Then, you can use that method when creating an instance of `LisScoreReceivedEvent` [here](https://github.com/oat-sa/extension-tao-lti-consumer/blob/master/model/result/ResultService.php#L132). The later option will also require you to change the basic outcome claim factory [here](https://github.com/oat-sa/extension-tao-lti-consumer/blob/master/model/Tool/Factory/Lti1p3DeliveryLaunchCommandFactory.php#L64), and use that new method. The second option is a little bit cleaner as apparently we prefix the IDs depending on the storage in TAO, but requires a bit more changes.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/2943256/190635437-5c1f925e-8a4a-4e53-a7d0-8fb9c0d37b9e.png">

2022-09-16 13:55 UTC, gabrielfs7 commented on model/execution/OntologyService.php
> +    protected function getKernelClass($classURI)
You do not need this, you can mock ontology in your test. I do not recommend to create this type of methods unless it is the only way.

How:

- Include OntologyAwareTrait in your class.
- use '$executionClass = $this->getClass(DeliveryExecutionInterface::CLASS_URI)';

Then, in your test, you can just mock ontology using `OntologyMockTrait` or better, faking the ServiceManager and injecting ontology.

2022-09-16 13:58 UTC, gabrielfs7 commented on test/unit/model/execution/OntologyServiceTest.php
> +            ['getKernelClass']
Check https://github.com/oat-sa/extension-tao-delivery/pull/555/files#r973052736, please. You do not need this method.

Introducing non private methods makes harder to refactor the code without breaking change and can have side effects. I know that in this case, TAO is a mistery and this other approach I mentioned probably is not so well shared

2022-09-16 14:01 UTC, gabrielfs7 commented on model/execution/DeliveryExecution.php
> +    public function getOriginalIdentifier()
you can use @inherited annotation to avoid repeating text :) 

Btw, I do not think you need to explain what this methods does in the docs ;)

2022-09-16 14:02 UTC, gabrielfs7 commented on model/execution/DeliveryExecution.php
> +    public function getOriginalIdentifier()
return type

```suggestion
    public function getOriginalIdentifier(): string
```

2022-09-16 14:42 UTC, kilatib commented on test/unit/model/execution/OntologyServiceTest.php
> +            ['getKernelClass']
Sorry, provided link doesn't work for me, also without this method, it creates too many difficulty. to cover it with unittest

2022-09-16 14:54 UTC, wazelin requested changes

2022-09-16 15:56 UTC, gabrielfs7 commented on test/unit/model/execution/OntologyServiceTest.php
> +            ['getKernelClass']
I fixed the link

2022-09-16 21:18 UTC, kilatib commented
@wazelin @gabrielfs7 All correction applied that is updated demo 


https://user-images.githubusercontent.com/2750628/190760754-15d01e4c-69f0-4d81-b971-ad399a690ab0.mov

2022-09-19 07:44 UTC, wazelin requested changes

2022-09-19 07:44 UTC, wazelin commented on model/execution/DeliveryExecutionInterface.php
> +    public function getOriginalIdentifier(): string;
Adding a new method to an interface is a breaking change.

Can it be mitigated by introducing a new interface?

2022-09-19 07:44 UTC, wazelin commented on model/execution/KVDeliveryExecution.php
> +        return str_replace(KeyValueService::DELIVERY_EXECUTION_PREFIX, '', $this->id);
This is still unsafe.

```suggestion
        return substr($this->id, strlen(KeyValueService::DELIVERY_EXECUTION_PREFIX));
```

Same applies to the RDS storage repository.

2022-09-19 09:52 UTC, poyuki commented on model/execution/rds/RdsDeliveryExecutionService.php
> +    public function spawnDeliveryExecution(string $label, string $deliveryId, string $userId, string $status, string $deliveryExecutionId = null)
not sure but isn't it's a breaking change?

2022-09-19 09:56 UTC, kilatib commented on model/execution/rds/RdsDeliveryExecutionService.php
> +    public function spawnDeliveryExecution(string $label, string $deliveryId, string $userId, string $status, string $deliveryExecutionId = null)
If parameter not provided it behaviour as it was

2022-09-19 09:57 UTC, poyuki commented on model/execution/rds/RdsDeliveryExecutionService.php
> +    public function spawnDeliveryExecution(string $label, string $deliveryId, string $userId, string $status, string $deliveryExecutionId = null)
i mean explicit type hinting

2022-09-19 10:28 UTC, poyuki approved these changes

2022-09-20 14:42 UTC, wazelin approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2022-09-20 14:44 UTC, wazelin commented
@kilatib, as a next step, please focus on _deploying_ all the feature/fix branches to a throw-away environment, and then linking it to the oat-dev test runner as a platform.

@poyuki will assist you with that ;)

Let's merge only _after_ a verification by QA engineers.

2022-09-23 08:08 UTC, kilatib commented
Tested and verified by QA on kitchen

2022-09-23 08:08 UTC, merged